## processing Swedish SuperLIM project https://spraakbanken.gu.se/en/resources/superlim#LexSemChange
## Sentiment analysis https://spraakbanken.gu.se/resurser/absabank-imm

In [1]:
import os , sys
import numpy as np
import pandas as pd
""" do not concatenate 
glue_path='/workspace/SVdata/SuperLimSE/'
sentiment_path=glue_path+'split10_consecutive_average/'
files=os.listdir(sentiment_path)
df_train=[]
df_test=[]
df_dev=[]
train_cnt=0
test_cnt=0
dev_cnt=0

for ds in files:     
    if 'train' in ds :
        #print("processing train tsv : ", ds)
        tempdf=pd.read_csv(sentiment_path+ds,sep='\t') 
        train_cnt+=len(tempdf)
        # collect all trainxx to df_train
        df_train.append(tempdf)
    elif 'test' in ds :
        #print("processing test tsv : ", ds)
        tempdf2=pd.read_csv(sentiment_path+ds,sep='\t')
        test_cnt+=len(tempdf2)
        # collect all testxx to df_test
        df_test.append(tempdf2)
    elif 'dev' in ds:
        #print("processing dev tsv : ", ds)
        tempdf3=pd.read_csv(sentiment_path+ds,sep='\t')
        dev_cnt+=len(tempdf3)
        # collect all devxx to df_dev
        df_dev.append(tempdf3)
    else:
        print("should only be train, test, dev in skipping ", ds)
        pass
print("train cnt accumulated: ",train_cnt)   
print("test cnt accumulated: ",test_cnt)
print("dev cnt accumulated: ",dev_cnt)"""

train cnt accumulated:  38640
test cnt accumulated:  4830
dev cnt accumulated:  4830

In [32]:
import os , sys
import numpy as np
import pandas as pd

glue_path='/workspace/SVdata/SuperLimSE/'
sentiment_path=glue_path+'split10_consecutive_average_tsv/'
train_df=pd.read_csv(sentiment_path+'train00.tsv', sep='\t')
test_df=pd.read_csv(sentiment_path+'test00.tsv', sep='\t')
dev_df=pd.read_csv(sentiment_path+'dev00.tsv', sep='\t')
len(train_df), len(test_df), len(dev_df)

(3860, 484, 486)

In [33]:
train_df.index[-1]
train_idx=[i for i in range(3860)]
len(train_idx), len(train_df)
train_df['index']=train_idx
train_df.tail()

,doc,par,text,label,label_simple,index
3855,z02107_flashback-15247839,4,"Nu var de, enligt dem själva, kristna också = ...",3.0,0,3855
3856,z02514_flashback-54883701,1,Professor varnar: bostäderna snart slut mestad...,2.0,-1,3856
3857,z02514_flashback-54883701,2,I SvD varnar professor Stellan Lundström att e...,2.0,-1,3857
3858,z02514_flashback-54883701,3,Att det är invandringen som spetsar till läget...,2.0,-1,3858
3859,z02514_flashback-54883701,4,Kommer inte detta ställa till stora motsättnin...,2.0,-1,3859

In [39]:
def label2num(x):
    LABELS = {'-1': 0, '0': 1 , '1' :2 }
    if type(x)==str:
        lb=LABELS[x]
    else:
        x=str(x)
        lb=LABELS[x]
    return lb
train_df['label_num']=train_df['label_simple'].apply(lambda x:label2num(x))
test_df['label_num']=test_df['label_simple'].apply(lambda x:label2num(x))
dev_df['label_num']=dev_df['label_simple'].apply(lambda x:label2num(x))
train_df.head(100)

,doc,par,text,label,label_simple,index,label_num
0,z02679_flashback-50294563,3,Förklarar regeringen och tidigare regeringars ...,3.0,0,0,1
1,z02679_flashback-50294563,5,Kom gärna med förslag på olika samband mellan ...,3.0,0,1,1
2,z01476_flashback-56524490,1,Sossarnas invandringspolitik bidrar till ännu ...,2.0,-1,2,0
3,z01476_flashback-56524490,3,Sossarna står ju främst för att dom vill ha et...,2.0,-1,3,0
4,z01476_flashback-56524490,10,Den nya invandrarklassen har fått det mycket s...,2.0,-1,4,0
...,...,...,...,...,...,...,...
95,z00126_www_svd_se_nyanlanda-bor-fa-stod-i-fem-...,1,Nyanlända bör få stöd i fem till sju år.,4.0,1,95,2
96,z00126_www_svd_se_nyanlanda-bor-fa-stod-i-fem-...,2,För nyanlända flyktingar bidrar staten med ett...,4.0,1,96,2
97,z00126_www_svd_se_nyanlanda-bor-fa-stod-i-fem-...,3,Ett fåtal av Sveriges kommuner bidrar till att...,4.0,1,97,2
98,z00126_www_svd_se_nyanlanda-bor-fa-stod-i-fem-...,5,"I Syrien råder det krig. Människor förföljs, t...",4.0,1,98,2
99,z00126_www_svd_se_nyanlanda-bor-fa-stod-i-fem-...,6,Men för att mottagandet skall bli bra krävs at...,4.0,1,99,2

In [40]:
train_df.label_simple.unique()

array([ 0, -1,  1])

(38640, 4830, 4830)

In [44]:
train_df.index[-1]

3859

In [45]:
begin=3859+1
df_test_index = [i+begin for i in range(len(test_df))]
test_df['index']=df_test_index
test_df.tail()

,doc,par,text,label,label_simple,label_num,index
479,www_aftonbladet_se_debatt_article22871619_ab,2,Sverige har genom historien hållit dörren öppe...,4.500000,1,2,4339
480,www_aftonbladet_se_debatt_article22871619_ab,3,Denna mångkultur har även fört med sig att vis...,2.428571,-1,0,4340
481,www_aftonbladet_se_debatt_article22871619_ab,4,Istället för att bearbeta alla fasor de har ut...,2.500000,-1,0,4341
482,www_aftonbladet_se_debatt_article22871619_ab,10,Att rikta sig till invandrargrupper genom att ...,3.000000,0,1,4342
483,www_aftonbladet_se_debatt_article22871619_ab,14,"När arbetslösheten är störst bland invandrare,...",2.800000,-1,0,4343

(4830, 4830)

In [9]:
df_test_all['index']=df_test_all_index

In [10]:
df_test_all.head()

,index,doc,par,text,label
38640,38640,z02679_flashback-50294563,3,Förklarar regeringen och tidigare regeringars ...,3.0
38641,38641,z02679_flashback-50294563,5,Kom gärna med förslag på olika samband mellan ...,3.0
38642,38642,z01476_flashback-56524490,1,Sossarnas invandringspolitik bidrar till ännu ...,2.0
38643,38643,z01476_flashback-56524490,3,Sossarna står ju främst för att dom vill ha et...,2.0
38644,38644,z01476_flashback-56524490,10,Den nya invandrarklassen har fått det mycket s...,2.0

43469

In [46]:
begin2=4343+1
dev_df_index=[i+begin2 for i in range(len(dev_df))]
dev_df['index']=dev_df_index
dev_df.tail()

,doc,par,text,label,label_simple,label_num,index
481,z01329_www_aftonbladet_se_debatt_debattamnen_p...,10,Vi kommer framöver att presentera ytterligare ...,2.0,-1,0,4825
482,z00394_flashback-59692401,1,Illegala invandrare Vs papperslösa.,1.0,-1,0,4826
483,z00394_flashback-59692401,2,"Är det bara svensk media som kör med ""Pappersl...",1.0,-1,0,4827
484,z00394_flashback-59692401,3,Ser ofta svenska artiklar om Trump och de ille...,1.0,-1,0,4828
485,z00394_flashback-59692401,4,Finns det något etablerat begrepp i engelskan ...,3.0,0,1,4829

In [13]:
len(df_dev_all_index), len(df_dev_all)

(4830, 4830)

In [14]:
df_dev_all.index=df_dev_all_index

In [15]:
df_dev_all['index']=df_dev_all_index

In [16]:
df_dev_all.head()

,index,doc,par,text,label
43470,43470,www_aftonbladet_se_debatt_a_gPG3xq_sd-har-fatt...,26,Respekt för mänskliga rättigheter är ett gemen...,4.333333
43471,43471,www_aftonbladet_se_debatt_a_gPG3xq_sd-har-fatt...,4,Mot enskilda mänskors strävan att ge sig själv...,3.428571
43472,43472,www_aftonbladet_se_debatt_a_gPG3xq_sd-har-fatt...,8,► ”Integrationspolitiken är ett totalt misslyc...,2.750000
43473,43473,www_aftonbladet_se_debatt_a_gPG3xq_sd-har-fatt...,15,Sverige har haft reglerad invandring under lån...,3.200000
43474,43474,www_aftonbladet_se_debatt_a_gPG3xq_sd-har-fatt...,17,Det avskyvärda kriget i Syrien har genererat s...,3.800000

In [ ]:
print(df_train_all.columns)
df_train_all.head()

In [17]:
out_dir=glue_path+'sentiment_processed/'
out_dir

'/workspace/SVdata/SuperLimSE/sentiment_processed/'

In [47]:
out_dir=glue_path+'sentiment_processed/'
train_df.to_csv(out_dir+'Processed_3classes_train00.tsv', index=False, sep='\t' )
test_df.to_csv(out_dir+'Processed_3classes_test00.tsv',index=False, sep='\t')
dev_df.to_csv(out_dir+'Processed_3classes_dev00.tsv',index=False,sep='\t')

In [12]:
df=pd.read_csv('/workspace/SVdata/SuperLimSE/sentiment_processed/Processed_dev00.tsv',sep='\t', )
df.head()

,doc,par,text,label,index
0,www_aftonbladet_se_debatt_article22871619_ab,5,Att vara intresserad av hemländernas politik ä...,3.000000,4344
1,www_aftonbladet_se_debatt_article22871619_ab,6,Tyvärr verkar det som om några partier har bli...,2.666667,4345
2,www_aftonbladet_se_debatt_article22871619_ab,7,Naturligtvis menar vi inte att politiker med u...,3.000000,4346
3,www_aftonbladet_se_debatt_article22871619_ab,8,Vi själva uppfostrades med en ideologi som vi ...,3.666667,4347
4,www_aftonbladet_se_debatt_article22871619_ab,9,Det gäller att vara öppen för förändring – men...,3.250000,4348

In [13]:
df.at[3,'index']

4347

In [34]:
str(round(float(df.iloc[1,-1])))

'3'

In [33]:
ids=list(df['index'].values)
#[43460, 43461, 43462, 43463, 43464, 43465, 43466, 43467, 43468, 43469]
n=len(ids)
for i in range(n)[:10]:
    print(type(int(df.iloc[i,0])), int(df.iloc[i,0]))

<class 'int'> 43470
<class 'int'> 43471
<class 'int'> 43472
<class 'int'> 43473
<class 'int'> 43474
<class 'int'> 43475
<class 'int'> 43476
<class 'int'> 43477
<class 'int'> 43478
<class 'int'> 43479

In [ ]:
import os , sys
import numpy as np
import pandas as pd

glue_path='/workspace/SVdata/SuperLimSE/'

out_dir=glue_path+'processed/'
print(out_dir)
LABELS = {'0': 0, '1': 1, '2': 2 , '3' :3 ,'4':4}
f=open(out_dir+'SV_sentiment_train.tsv', 'r')
lines=f.readlines()
print(len(lines))
"""
with open(out_dir+'SV_sentiment_train.tsv', 'r') as f:
    for i,line in enumerate(f):
        if i >0:
            row = line.strip().split('\t')
            try :
                label=str(round(float(row[-1].strip())))

            except:
                print(row[-1])
                print('\n')
                print(row[-2])
        else: pass
"""

## processing Swedish XNLI equavelent 
#### url :https://github.com/salesforce/xnli_extension/blob/master/data/multinli.train.sv.tsv 
#### !wget https://raw.githubusercontent.com/salesforce/xnli_extension/master/data/multinli.train.sv.tsv

In [ ]:
import os,sys
import numpy as np
import pandas as pd
df=pd.read_csv('/workspace/SVdata/SuperLimSE/multinli.train.sv.tsv', sep='\t')
print(len(df))
df.head()

In [ ]:
from sklearn.model_selection import train_test_split
X=df.iloc[:,[0,1]].values
y=df.iloc[:,-1].values
X_train, Xtmp, y_train, ytmp= train_test_split(X,y,test_size=0.4,stratify=y,random_state=1234)
X_train.shape, y_train.shape, Xtmp.shape, ytmp.shape

In [ ]:
X_test, X_dev, y_test, y_dev= train_test_split(Xtmp,ytmp,test_size=0.5,stratify=ytmp,random_state=1234)
X_test.shape, y_test.shape, X_dev.shape, y_dev.shape

In [ ]:
df_train=pd.DataFrame()

df_train['sentence1']=X_train[:,0]
df_train['sentence2']=X_train[:,1]
df_train['label']=y_train
df_train.insert(loc=0, column='index', value=df_train.index)
print(len(df_train))
df_train.head()

In [ ]:
#verify all LABELS are captured and there are no mis-labelled or mis-spelled label
LABELS = {'contradictory': 0, 'entailment': 1, 'neutral': 2}
for i,lb in enumerate(df_train['label']):
    if lb in LABELS:
        pass
    else:
        print(i,lb)

In [ ]:
df_test=pd.DataFrame()

df_test['sentence1']=X_test[:,0]
df_test['sentence2']=X_test[:,1]
df_test['label']=y_test
df_test.insert(loc=0, column='index', value=df_test.index)
print(len(df_test))
df_test.head()

In [ ]:
#verify all LABELS are captured and there are no mis-labelled or mis-spelled label
LABELS = {'contradictory': 0, 'entailment': 1, 'neutral': 2}
for i,lb in enumerate(df_test['label']):
    if lb in LABELS:
        pass
    else:
        print(i,lb)

In [ ]:
df_dev=pd.DataFrame()

df_dev['sentence1']=X_dev[:,0]
df_dev['sentence2']=X_dev[:,1]
df_dev['label']=y_dev
df_dev.insert(loc=0, column='index', value=df_dev.index)
print(len(df_dev))
df_dev.head()

In [ ]:
#verify all LABELS are captured and there are no mis-labelled or mis-spelled label
LABELS = {'contradictory': 0, 'entailment': 1, 'neutral': 2}
for i,lb in enumerate(df_dev['label']):
    if lb in LABELS:
        pass
    else:
        print(i,lb)

In [ ]:
glue_path='/workspace/SVdata/SuperLimSE/'
df_train.to_csv(glue_path+'SV_xnli_train.tsv', index=False, sep='\t' )
df_test.to_csv(glue_path+'SV_xnli_test.tsv', index=False, sep='\t' )
df_dev.to_csv(glue_path+'SV_xnli_dev.tsv', index=False, sep='\t' )

In [1]:
import os , sys
import numpy as np
import pandas as pd

sts_path='/workspace/SVdata/SuperLimSE/sts/'

train_df=pd.read_csv(sts_path+'train-sv.tsv', sep='\t')
test_df=pd.read_csv(sts_path+'test-sv.tsv', sep='\t')
dev_df=pd.read_csv(sts_path+'dev-sv.tsv', sep='\t')
train_df.head()

,genre,filename,sentence1,sentence2,score
0,main-captions,MSRvid,Ett plan tar fart.,Ett luftplan tar fart.,5.00
1,main-captions,MSRvid,En man spelar en stor flöjt.,En man spelar en flöjt.,3.80
2,main-captions,MSRvid,En man sprider strimlad ost på en pizza.,En man sprider strimlad ost på en okokt pizza.,3.80
3,main-captions,MSRvid,Tre män spelar schack.,Två män spelar schack.,2.60
4,main-captions,MSRvid,En man spelar cello.,En sittande man spelar cello.,4.25

In [3]:
print("train records count : ", len(train_df))
print("test records count : ", len(test_df))
print("dev records count : ", len(dev_df))

train records count :  5749
test records count :  1379
dev records count :  1500

In [23]:
def round2class(x):    
    return int(round(float(x)))

def shrink2three(x):
    x_=round2class(x)
    if x_==0:
        return 0
    elif 0<x_<=3:
        return 1
    elif 3<x_<=5:
        return 2
    else:
        print("x_:{} is not in [0,1,2]".format(str(x_)))

train_df['label']=train_df['score'].apply(lambda x : round2class(x))
test_df['label']=test_df['score'].apply(lambda x : round2class(x))
dev_df['label']=dev_df['score'].apply(lambda x : round2class(x))
train_df.head()

,genre,filename,sentence1,sentence2,score,label,index
0,main-captions,MSRvid,Ett plan tar fart.,Ett luftplan tar fart.,5.00,5,0
1,main-captions,MSRvid,En man spelar en stor flöjt.,En man spelar en flöjt.,3.80,4,1
2,main-captions,MSRvid,En man sprider strimlad ost på en pizza.,En man sprider strimlad ost på en okokt pizza.,3.80,4,2
3,main-captions,MSRvid,Tre män spelar schack.,Två män spelar schack.,2.60,3,3
4,main-captions,MSRvid,En man spelar cello.,En sittande man spelar cello.,4.25,4,4

In [14]:
train_df['index']=train_df.index
cur_index=train_df.index[-1]+1
n=len(test_df)
test_df['index']=[cur_index+i for i in range(n)]
test_df['index'].values[-1]
cur_index=test_df['index'].values[-1]+1
n=len(dev_df)
dev_df['index']=[cur_index+i for i in range(n)]

In [24]:
train_df.tail()

,genre,filename,sentence1,sentence2,score,label,index
5744,main-news,headlines,Alvorliga stormar som storm Clodagh träffar St...,Merkel lovar Natos solidaritet med Lettland,0.0,0,5744
5745,main-news,headlines,Dussintals egyptier gisslan tagna av libyska t...,Dödstalet för egyptisk båtkrasch ökar när fler...,0.0,0,5745
5746,main-news,headlines,President på väg till Bahrain,President Xi: Kina fortsätter att hjälpa till ...,0.0,0,5746
5747,main-news,headlines,"Kina, Indien lovar ytterligare bilaterala band",Kina går igenom för att försäkra jittery aktie...,0.0,0,5747
5748,main-news,headlines,Putins talesman: Dopningsavgifter verkar ogrun...,Det senaste om svårt väder: 1 död i Texas efte...,0.0,0,5748

In [25]:
test_df.head()

,genre,filename,sentence1,sentence2,score,label,index
0,main-captions,MSRvid,En flicka stylar håret.,En flicka borstar håret.,2.5,2,5749
1,main-captions,MSRvid,En grupp män spelar fotboll på stranden.,En grupp pojkar spelar fotboll på stranden.,3.6,4,5750
2,main-captions,MSRvid,En kvinna mäter en annan kvinnas fotled.,En kvinna mäter en annan kvinnas fotled.,5.0,5,5751
3,main-captions,MSRvid,En man skär upp en gurka.,En man skär en gurka.,4.2,4,5752
4,main-captions,MSRvid,En man spelar en harpa.,En man spelar ett tangentbord.,1.5,2,5753

In [26]:
test_df.tail()

,genre,filename,sentence1,sentence2,score,label,index
1374,main-news,headlines,"Filippinerna, Kanada lovar att ytterligare öka...",Filippinerna sparar 100 efter att färjan sjunkit,0.0,0,7123
1375,main-news,headlines,Israel utestänger palestinier från Jerusalems ...,"Tvåstatslösning mellan palestinier, Israel kak...",1.0,1,7124
1376,main-news,headlines,Hur mycket vet du om Secret Service?,Lagstiftare från båda sidor uttrycker upprördh...,1.0,1,7125
1377,main-news,headlines,Obama kämpar för att lugna saudiska rädslor nä...,Myanmar kämpar för att slutföra röstlängder fö...,0.0,0,7126
1378,main-news,headlines,Sydkorea förklarar slut på MERS-utbrott,Nordkoreas delegation träffas med sydkoreanska...,0.0,0,7127

In [27]:
dev_df.head()

,genre,filename,sentence1,sentence2,score,label,index
0,main-captions,MSRvid,En man med en hård hatt dansar.,En man som bär en hård hatt dansar.,5.00,5,7128
1,main-captions,MSRvid,Ett litet barn rider på en häst.,Ett barn rider på en häst.,4.75,5,7129
2,main-captions,MSRvid,En man matar en mus till en orm.,Mannen matar en mus till ormen.,5.00,5,7130
3,main-captions,MSRvid,En kvinna spelar gitarren.,En man spelar gitarr.,2.40,2,7131
4,main-captions,MSRvid,En kvinna spelar flöjten.,En man spelar en flöjt.,2.75,3,7132

In [31]:
dev_df.label.unique()

array([5, 2, 3, 4, 1, 0])

In [28]:
out_path=sts_path+'5classes/'
train_df.to_csv(out_path+'SV_STS_train_with_index.tsv', index=False, sep='\t' )
test_df.to_csv(out_path+'SV_STS_test_with_index.tsv', index=False, sep='\t' )
dev_df.to_csv(out_path+'SV_STS_dev_with_index.tsv', index=False, sep='\t' )